import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	tutorialSidebar: [{ type: "autogenerated", dirName: "tutorial" }],
	mianshiSidebar: [{ type: "autogenerated", dirName: "mianshi" }],
	css3Siderbar: [{ type: "autogenerated", dirName: "css3" }],
	foundrySiderbar: [{ type: "autogenerated", dirName: "foundry" }],
	golangSiderbar: [{ type: "autogenerated", dirName: "golang" }],
	passkeySiderbar: [{ type: "autogenerated", dirName: "passkey" }],
	smartWalletSiderbar: [{ type: "autogenerated", dirName: "smart-wallet" }],
	lightweightSiderbar: [{ type: "autogenerated", dirName: "lightweight" }],
	uniswapSiderbar: [{ type: "autogenerated", dirName: "uniswap" }],
};

export default sidebars;
