import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    blockchainSidebar: [{ type: "autogenerated", dirName: "blockchain" }],
    css3Sidebar: [{ type: "autogenerated", dirName: "css3" }],
    devcontainerSidebar: [{ type: "autogenerated", dirName: "devcontainer" }],
    feSidebar: [{ type: "autogenerated", dirName: "fe" }],
    gitSidebar: [{ type: "autogenerated", dirName: "git" }],
    golangSidebar: [{ type: "autogenerated", dirName: "golang" }],
    learnSidebar: [{ type: "autogenerated", dirName: "learn" }],
    lightweightSidebar: [{ type: "autogenerated", dirName: "lightweight" }],
    opsSidebar: [{ type: "autogenerated", dirName: "ops" }],
    rustSidebar: [{ type: "autogenerated", dirName: "rust" }],
    solanaSidebar: [{ type: "autogenerated", dirName: "solana" }],
    swiftuiSidebar: [{ type: "autogenerated", dirName: "swiftui" }],
    tutorialSidebar: [{ type: "autogenerated", dirName: "tutorial" }],
    xmindSidebar: [{ type: "autogenerated", dirName: "xmind" }],
};

export default sidebars;
