#!/bin/bash

# Define the path to the sidebars.ts file
SIDEBARS_FILE="sidebars.ts"

# Start writing the new content to the sidebar file
echo 'import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";' > $SIDEBARS_FILE
echo '' >> $SIDEBARS_FILE
echo "// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)" >> $SIDEBARS_FILE
echo '' >> $SIDEBARS_FILE
echo '/**' >> $SIDEBARS_FILE
echo ' * Creating a sidebar enables you to:' >> $SIDEBARS_FILE
echo ' - create an ordered group of docs' >> $SIDEBARS_FILE
echo ' - render a sidebar for each doc of that group' >> $SIDEBARS_FILE
echo ' - provide next/previous navigation' >> $SIDEBARS_FILE
echo '' >> $SIDEBARS_FILE
echo ' The sidebars can be generated from the filesystem, or explicitly defined here.' >> $SIDEBARS_FILE
echo '' >> $SIDEBARS_FILE
echo ' Create as many sidebars as you want.' >> $SIDEBARS_FILE
echo ' */' >> $SIDEBARS_FILE
echo 'const sidebars: SidebarsConfig = {' >> $SIDEBARS_FILE

# Iterate over each directory in the /docs directory
for dir in docs/*/; do
  # Remove the trailing slash
  dirname=${dir%/}
  # Extract the base directory name
  baseDir=$(basename "$dirname")
  # Capitalize the first letter and append "Sidebar"
  sidebarKey=$(echo "$baseDir" | awk '{print tolower(substr($0, 1, 1)) substr($0, 2) "Sidebar"}')
  # Append the sidebar entry to the file
  echo "    $sidebarKey: [{ type: \"autogenerated\", dirName: \"$baseDir\" }]," >> $SIDEBARS_FILE
done

# Close the sidebars object
echo '};' >> $SIDEBARS_FILE
echo '' >> $SIDEBARS_FILE
echo 'export default sidebars;' >> $SIDEBARS_FILE

echo "sidebars.ts has been updated."
